adam: false
batch_size: 4
bucket: ''
cache_images: false
cfg: ''
data: ./Yolov5Train/data/exp.yaml
device: ''
entity: null
epochs: 300
evolve: false
exist_ok: false
hyp: .\Yolov5Train\data\hyp.scratch.yaml
image_weights: false
img_size:
- 640
- 640
linear_lr: false
local_rank: -1
log_artifacts: false
log_imgs: 16
multi_scale: false
name: exp
noautoanchor: false
nosave: false
notest: false
project: runs/train
quad: false
rect: false
resume: false
single_cls: false
sync_bn: false
weights: yolov5s.pt
workers: 8
world_size: 1
global_rank: -1
save_dir: runs\train\exp3
total_batch_size: 4
